### ISSUE TITLE
Add contact info / page

### ISSUE THREAD

**Issue by bucaran** [Kcetry/Kcetry.github.io#1]
Hi, it would be useful if your site had a contact page in order to get in touch w/ you.

Cheers.

**Comment by Kcetry** [comment]
I got it.  ha ha.. :)

**Comment by bucaran** [comment]
If you prefer to keep your privacy I understand :smile: 

I would like to send you an email, so if you can say hi to jbucaran@me.com that'd be great!

**Comment by Kcetry** [comment]
Yeah,I would.

**Comment by bucaran** [comment]
Great! Thanks.
